### ISSUE TITLE
Starboard down

### ISSUE THREAD

**Issue by MJHeijster** [TheNoob27/starboard-issues#21]
Yesterday we noticed on our server that Starboard isn't working anymore. I also noticed that it doesn't work on another server. Any known issues?

**Comment by ghostlylake** [comment]
Check the [support server](https://discord.gg/rZgxfbH) for information related to downtime.

Copied from the [#announcements](https://discord.com/channels/654955982971076609/655718104143233024) channel


> @everyone it's with a heavy heart that I have to announce the bot has suffered from a major **data loss**.
> All filters and channel settings are gone, and all setting changes, leaderboard data, reward roles and starred messages created after **January 2021** have been lost too. I'm really sorry for the inconvenience.
> 
> ---
> Why?
> On Monday, the bot went offline. It wasn't my doing, and it was offline longer than usual so I decided to investigate. I couldn't figure out how to bring it back online so I emailed my server provider. They responded saying my server was "_out of service_" and all data had been lost.
> 
> Since Tuesday I've been working really hard to try and negotiate with my server provider. I spoke with several different people because I believed there was a chance I could get my data back, which there was. My data is present on the hard drive of the server, but the server itself is inaccessible. But eventually it had been decided by them yesterday that there would be no way I could get my data back without being disruptive to other server users, so now I have to live with that.
> 
> The bot's database had been being backed up, but backups were saved on the server instead of a separate location because I forgot to take into account chances of the server itself failing like this.
> 
> What does this mean for starred messages?
> **All messages can still get starred.** If you star a message in the starboard, the bot will be able to find the original message, stars will be refreshed and stats will be added back. However if you star the original message, the bot will post a new message to the starboard, as it is unable to find a starboard message from a normal message. But if you then react on the old starboard message, it will be considered a duplicate and be removed in favour of the new starboard message.
> 
> I'm once again really sorry and can only promise you this won't happen again.
> Thank you all so much for your extreme patience. <3


> The bot will be offline for a little while longer though, I'm in the process of purchasing a new server to host the bot on, so bare with me.
> This is a really bad time for all this to unfold because I really should be focusing on school as I have exams coming up, but I can't just abandon this.
> But ideally the bot should be back online tomorrow or the day after

**Comment by MJHeijster** [comment]
Closing this, issue has been resolved, just have to be mindful that we have reposts in the starboard channel.

**Comment by theCapypara** [comment]
Hi, we noticed the info/settings got reset again, is there still an issue? If so could you reopen this?
